# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cv_related_test',
                'doc_host': 'https://HasanGoni.github.io',
                'git_url': 'https://github.com/HasanGoni/cv_related_test',
                'lib_path': 'cv_related_test'},
  'syms': {'cv_related_test.core': {'cv_related_test.core.foo': ('core.html#foo', 'cv_related_test/core.py')}}}
